name: Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: |
        cmake --build build --config Debug

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure --verbose

    - name: Setup python
      uses: actions/setup-python@v4
      if: contains(matrix.os, 'ubuntu')
      with:
        python-version: 3.9

    - name: Upload code coverage to coveralls
      if: contains(matrix.os, 'ubuntu')
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools cpp-coveralls
        coveralls -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --exclude "venv" --exclude "build/_deps"

    #- name: Coveralls
    #  uses: coverallsapp/github-action@master
    #  with:
    #    path-to-lcov: build/lcov.info
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
